name: ConvCNP
kwargs:
  x_min: -2.0
  x_max: +2.0
  r_dim: 64
  cnn_dims: null  # use default
  cnn_xl: False
  on_the_grid: False
  points_per_unit: 64
  x_margin: 0.1
  min_sigma: 0.1
train_kwargs: {}
valid_kwargs: {}
test_kwargs: {}
